---
name: Publish to Docker Registry
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hden/run-env/main
          username: hden
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
